version: "3"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: simple-fastapi
      SECRET_KEY: 2392e3p2ke2p3okep23o0ek23023k2pko3e;2podjko23hfoinonwlkdfjwlkj
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUITES: 60
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple-fastapi
    ports:
      - "5432:54432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
