version: "3"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple-fastapi
    ports:
      - "54432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # - <sync_local_dir>:<sync_docker_dir>:<security_command>
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: simple-fastapi
      SECRET_KEY: 2392e3p2ke2p3okep23o0ek23023k2pko3e;2podjko23hfoinonwlkdfjwlkj
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUITES: 60
    depends_on:
      - postgres

volumes:
  postgres_data:
