name: Build and Deploy Code

# on:
#   push:
#     branches:
#       - "main"
#       - "anotherbranch"
#   pull_request:
#     branches:
#       - "test_branch"
on: [push, pull_request]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Hello shahin
        run: echo "__Hello__"